### PR TITLE
Right on red & new HearseAI

### PR DESCRIPTION
**Pull request by thardie**
Right on red (or left on red if map in left hand drive mode) allows vehicles to turn on red after stop. Can also be controlled per segment in the junction restriction manager

The new Hearse AI does the following:
- When new dead person needs to be picked up, checks to see if any other hearse is already going past that building, and if so, queues it to pick up. If it finds one, the original one that was scheduled to pick it up is marked as "not in use"
- If no vehicle is going past, checks if a "not in use" vehicle is closer (straight line) to the pick up point than the game picked one
- If a building has a high problem, doesn't use the queuing method, but rather the closest vehicle.

Added some minor debugging stuff:
- Ability to see all hearse or garbage trucks paths as they go into action
- Improved debug log performance significantly (You can now actually exit to main menu in a normal time in debug builds)

### CODE REVIEW

**Comment by VictorPhilipp** [comment]
Don't know why I closed this. I like the right on red feature. However, there are other mods out there that offer custom AIs for service vehicles. I am unsure whether such a feature should be added to TMPE since the mod is already very bloated.

**Comment by adiac** [comment]
Yes, TMPE has lot of features. I looked in the workshop and there are some other mods that manage the AI of service vehicles, but they all seem outdated and do not work for the current SC version.

So the Service Vehicles are a part of traffic right? It would be a nice feature and make traffic some what more efficient.

**Comment by DaEgi01** [comment]
Well my advice is that TM:PE should focus only on how a vehicle gets from point a to point b,
and the other AI mods should mess with the dispatcher to tell if a vehicle should get from a to b in the first place. but i guess the difference is not always that easy to tell, for example because of a more complex parking logic or because something happens on the way from a to b that affects the dispatching process.

**Comment by thardie** [comment]
The reason I coded this in TM:PE is that the other mods are not just out dated. They are incompatible with TM:PE's Vehicle AI. IE, you can load them, then the 2 mods just argue with each other. I couldn't make any of the others work, and that was my motivation to build the HearseAI.

**Comment by DaEgi01** [comment]
I used to use https://steamcommunity.com/sharedfiles/filedetails/?id=512341354 but have not tested if it works with ParkLife.

**Comment by thardie** [comment]
Central Services Dispatcher documentation states it's incompatible with TM:PE.

**Comment by DaEgi01** [comment]
Central Services Dispatcher states:
"There are unconfirmed reports of Traffic Manager: President Edition causing problems for garbage trucks."
I would not count that as fact.

**Comment by VictorPhilipp** [comment]
I have checked CSD's code multiple times manually in the past and could not identify any incompatibilities with TMPE.

**Comment by thardie** [comment]
Fair enough. I'll try and find some time to separate out the hearseAI code.

**Comment by DaEgi01** [comment]
its not that i have any decision in that matter, i am not one of the TM:PE devs, so VictorPhilipp can do as he pleases. I just think that a clear and "narrow" scrope for TM:PE benefits the mod and the community in general. more focus, less bugs, better interoperability and modularity etc. 
we definitely need a up to date mod that manages the dispatching, and handling of the cases that you have tackled with your HearseAi changes. I'd rather see them in another mod though.
I try to get in contact with Jonas, the author of CSD to find out if he is willing to continue with his mod or just support it by taking in pull requests.
There are other mods like that "Districts Service Limit 3.0" for example but I was under the impression that CSD is the best of them. Maybe your changes would best be integrated there or in a completely new mod altogether.

**Comment by thardie** [comment]
Yeah, I didn't mean I was just going to throw it away, rather factor it out into a separate commit so we can pull the features into the mainline independently.

**Comment by aubergine10** [comment]
Speaking as an end-user:

1. I would certainly like to see better **Hearse AI** - if for no other reason than to better handle deathwaves.
2. I would prefer it as separate mod - I see **TM:PE** as a sort of generic traffic management mod, IMO it should not be service-specific.
3. I use [**District Service Limit 3.0**](https://steamcommunity.com/sharedfiles/filedetails/?id=1181352643&searchtext=district) to constrain services to designated districts (they can be set up to cover multiple specified districts or even entire map, per service building) - if you release separate Hearse AI it would be great if it was compatible with DSL3.
4. **Fire AI** is also terrible - with spreading fire, an engine will put one fire out then go back to base while the building next door is still on fire. A fire AI mod that makes fire engine check if next door is on fire (and if so help tackle the blaze) before going home would be great!

**Comment by ntoff** [comment]
Any news on this? I got excited when I saw a closed PR for right on red thinking it was merged (then saw it was now combined here).

**Comment by thardie** [comment]
Sorry, have not been able to find time to do any more work on this yet. I agreed I would separate Right on red and the hearseAI into separate changes. I cannot, however, separate HearseAI away from TM:PE, since it uses TM:PE's routing engine. I would have to come up with a mod that works in conjunction with TM:PE, which is a lot more work.

**Comment by ntoff** [comment]
It's cool, the hearse AI in the game does indeed suck, but more important I think are fixing major root traffic issues like massive lines of traffic backing up for miles that would benefit from being able to turn on a red in a dedicated turning lane.

I forked TMPE and manually merged your right on red changes by themselves just to tide me over, works great! Thanks.

**Comment by aubergine10** [comment]
There is a [new Hearse AI](https://steamcommunity.com/sharedfiles/filedetails/?id=1456061226) in the workshop  which potentially resolves the Hearse issues.

**Comment by ntoff** [comment]
I'm subscribed to that one but I don't think it actually fixes the hearse AI, it just alters the emptying mechanic.

I hope you find a way to fix the hearse AI, I've seen a couple of other hearse AI mods but the comments point to them conflicting with TMPE, it'd be nice to have one that definitely, 100%, works together with TMPE.

Can mods have mods? Like, could you write a hearse AI mod that requires TMPE? So it doesn't do anything on its own, but when installed along side TMPE, it plugs into TMPE's routing engine? I see a few mods that rely on a base "framework" mod.

**Comment by FireController1847** [comment]
I hate to be "that guy" but what's the status on right-on-red? Would it not be better to make it a separate PR so it can get in, without having to wait for the hearse AI?

**Comment by ntoff** [comment]
The red on right needs a bit more work I think, I'm noticing that people are turning right into traffic that has the right of way.

image
Traffic from the bottom is turning right into the traffic from the left which would have the right of way, causing it to stop for the traffic from the bottom. It seems like right on red would need to be refined to only allow traffic to move if the traffic lights are set up to only allow movement in one direction at a time (is that even possible?) so cars don't turn into moving traffic.

It seems to work well for traffic that turns right from a main road into a side road, when the main lights are red then cars can still turn into the side street, but it fails when the main lights are green, allowing cars from the side street to enter into moving traffic.

**Comment by FireController1847** [comment]
I don't know if this is possible as I'm not the best c# programmer and I know very little about the mod, but could we make it so that when someone is turning right and the light is green, there has to be a certain distance between the car going straight and the car turning right? For example, if the car going straight is less than x distance to the turn, do NOT turn right

**Comment by thardie** [comment]
I haven't figured out how to find other cars approaching the intersection that a right on red could interfere with. I have seen a little of what you're talking about, and I've seen people in RL do that too (sneak a space in right on red when they probably shouldn't have). In the cases where it's bad at certain intersection, just edit the intersection rules and disable right on red for that particular turn.

**Comment by FireController1847** [comment]
Odd, I've been testing your code on the latest version and I have yet to see someone pull into moving traffic; although I am having issues with people in the farmost right lane, going straight (no right turn there), going through a red.

**Comment by FireController1847** [comment]
I'm unable to really recreate your situation... I'm noticing a lot of "jerks" pulling in front of left-turns, but all-in-all it's not that unrealistic. Just more jerkiness in people in cities skylines than in real life haha.

I have the code ready to put in a seperate PR, if you want. I/we just need to fix this bug of going straight through a red, when in the right lane with no right turn.

**Comment by thardie** [comment]
I think I already fixed this in my local version. This is when there is no right turn at all and only straight and they go straight on red, right?

**Comment by FireController1847** [comment]
Right

**Comment by FireController1847** [comment]
Would you be up for explaining some of this to me? I want to get into CS modding, but I have no idea where to start and I think helping contribute to some things could help. I want to know more about TMPE in general, and I'd love it if you could explain some of the car-code to me.

What's your preferred method of communication? Preferably, an instant messenger would work best. I'm `FireController1847#3577` on Discord, if you want to add me. It'd be great if we could chat about this.

**Comment by thardie** [comment]
I spent about 4 hours on this this weekend. I factored out the code, and tested it. Still does the right on red in the straight scenario :(

I tried to fire up my debug environment, but seems something in the last 6 months has broken my mono debugger. (mono dlls don't get reported to the debugger with full paths anymore, just "data-0xxxxxxxx" , which means we don't know what mdb file to load for symbols.) I've run out of time for this weekend. I'll come back to it in the next few days or next weekend to keep working on it.

**Comment by Xyrhenix** [comment]
Any progress? It's been a while and I remember someone commenting on the Workshop file asking about this feature.

**Comment by VictorPhilipp** [comment]
Implemented in 1.10.6 labs

**Pull request closed without merging**
