### PR TITLE
 update lang_zh.txt

### PR DESCRIPTION
**Pull request by Emphasia**
update Simplified-Chinese translation

### CODE REVIEW

**Comment by originalfoo** [comment]
@Emphasia Thanks for the update, however we've moved to a new repository: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition

You'll also find the latest locale files in that repository (there's a few pull requests that will also add some additional language strings in the next few days).

**Comment by Emphasia** [comment]
@aubergine10 
I'm aware of that repo.
And the reason I created this PR here is because it's a patch to stable that should be included in 10.17 release (but I missed it 😂).
As for the currently developing features, I have added suggestions in the corresponding PR. (https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/285#pullrequestreview-228653300 & https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/286#pullrequestreview-228655163)

**Comment by originalfoo** [comment]
Both stable and labs versions of the mod are being developed in the other repo.

**Comment by Emphasia** [comment]
> Both stable and labs versions of the mod are being developed in the other repo.

and I will create PR there when dealing with keys added there (which is all from now on). 😃

**Pull request closed without merging**
